/** @typedef {{ tx: number, ty: number }} Tile */

(() => {
const TILE = 16;
const WORLD_PX = 24;

/** @type {readonly { id: string, name: string, role: string, portrait: string, sheet?: { cellW: number, cellH: number, idle: number, walk: readonly number[], foot: number, scale: number, dirs: Record<string, number> } }[]} */
const CHARACTERS = [
  {
    id: "ima",
    name: "Ima",
    role: "Cantante",
    portrait: "assets/ima-walk.png?v=18",
    sheet: {
      cellW: 65,
      cellH: 94,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 94,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "tobi",
    name: "Tobi",
    role: "Guitarra",
    portrait: "assets/tobi-walk.png?v=18",
    sheet: {
      cellW: 52,
      cellH: 80,
      idle: 0,
      walk: [0, 1, 2, 3],
      foot: 2,
      scale: WORLD_PX / 80,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "negro",
    name: "El Negro",
    role: "Teclado",
    portrait: "assets/negro-walk.png?v=20",
    sheet: {
      cellW: 117,
      cellH: 159,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 159,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "alvin",
    name: "Alvin",
    role: "Saxo",
    portrait: "assets/alvin-walk.png?v=21",
    sheet: {
      cellW: 110,
      cellH: 146,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 146,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "ger",
    name: "Ger",
    role: "Batería",
    portrait: "assets/ger-walk.png?v=24",
    sheet: {
      cellW: 124,
      cellH: 150,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 150,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "colito",
    name: "Colito",
    role: "Bajo",
    portrait: "assets/colito-walk.png?v=23",
    sheet: {
      cellW: 123,
      cellH: 154,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 154,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "nacho",
    name: "Nacho",
    role: "Timbales",
    portrait: "assets/nacho-walk.png?v=27",
    sheet: {
      cellW: 104,
      cellH: 134,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 134,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "jerry",
    name: "Jerry",
    role: "Güiro",
    portrait: "assets/jerry-walk.png?v=27",
    sheet: {
      cellW: 104,
      cellH: 136,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 136,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
];

/**
 * @param {readonly string[]} rows
 * @returns {readonly string[]}
 */
function rowsOf(rows) {
  const width = rows[0].length;
  for (const row of rows) {
    if (row.length !== width) {
      throw new Error("Mapa con filas de distinto ancho");
    }
  }
  return rows;
}

function blankRows(width, height) {
  const wall = "#".repeat(width);
  const open = `#${".".repeat(width - 2)}#`;
  const rows = [wall];
  for (let y = 1; y < height - 1; y += 1) {
    rows.push(open);
  }
  rows.push(wall);
  return rowsOf(rows);
}

const PASILLO_ROWS = rowsOf([
  "################################################",
  "################################################",
  "################################################",
  "################################################",
  "################################################",
  "################################################",
  "################################################",
  "###...####...####..#####...#####...###bbb#######",
  "#...........................##........bbb......#",
  "#..............................................#",
  "#..............................................#",
  "################################################",
  "################################################",
  "################################################",
  "################################################",
  "################################################",
]);

const ROOM_ROWS = rowsOf([
  "################",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#......dd......#",
  "################",
]);

/**
 * @param {string} id
 * @param {string} name
 * @param {readonly [string, string]} floor
 * @param {string} line
 */
function room(id, name, floor, line) {
  return {
    id,
    name,
    rows: ROOM_ROWS,
    floor,
    wall: "#1a120e",
    spawn: { tx: 7, ty: 10 },
    exits: [
      { tx: 6, ty: 12 },
      { tx: 7, ty: 12 },
      { tx: 8, ty: 12 },
      { tx: 9, ty: 12 },
    ],
    coin: { id, tx: 8, ty: 3 },
    npcs: [{ tx: 4, ty: 8, name: "Alguien del lugar", lines: [line, "Hay una moneda en el piso."] }],
    doors: [],
    counter: false,
  };
}

const MAPS = {
  pasillo: {
    id: "pasillo",
    name: "Pasillo",
    rows: PASILLO_ROWS,
    floor: ["#3a3128", "#332b23"],
    wall: "#1a120e",
    spawn: { tx: 8, ty: 10 },
    exits: [],
    coin: null,
    npcs: [],
    doors: [
      {
        tx: 3,
        ty: 7,
        to: "frawens",
        label: "Casa Frawens",
        spawnThere: { tx: 10, ty: 25 },
        spawnBack: { tx: 4, ty: 9 },
      },
      {
        tx: 4,
        ty: 7,
        to: "frawens",
        label: "",
        spawnThere: { tx: 10, ty: 25 },
        spawnBack: { tx: 4, ty: 9 },
      },
      {
        tx: 5,
        ty: 7,
        to: "frawens",
        label: "",
        spawnThere: { tx: 10, ty: 25 },
        spawnBack: { tx: 4, ty: 9 },
      },
      {
        tx: 10,
        ty: 7,
        to: "tilos",
        label: "Los Tilos",
        spawnThere: { tx: 20, ty: 15 },
        spawnBack: { tx: 11, ty: 9 },
      },
      {
        tx: 11,
        ty: 7,
        to: "tilos",
        label: "",
        spawnThere: { tx: 20, ty: 15 },
        spawnBack: { tx: 11, ty: 9 },
      },
      {
        tx: 12,
        ty: 7,
        to: "tilos",
        label: "",
        spawnThere: { tx: 20, ty: 15 },
        spawnBack: { tx: 11, ty: 9 },
      },
      {
        tx: 17,
        ty: 7,
        to: "universal",
        label: "Universal",
        spawnThere: { tx: 11, ty: 26 },
        spawnBack: { tx: 17, ty: 9 },
      },
      {
        tx: 18,
        ty: 7,
        to: "universal",
        label: "",
        spawnThere: { tx: 11, ty: 26 },
        spawnBack: { tx: 17, ty: 9 },
      },
      {
        tx: 24,
        ty: 7,
        to: "moreno",
        label: "Plaza Moreno",
        spawnThere: { tx: 54, ty: 29 },
        spawnBack: { tx: 25, ty: 9 },
      },
      {
        tx: 25,
        ty: 7,
        to: "moreno",
        label: "",
        spawnThere: { tx: 54, ty: 29 },
        spawnBack: { tx: 25, ty: 9 },
      },
      {
        tx: 26,
        ty: 7,
        to: "moreno",
        label: "",
        spawnThere: { tx: 54, ty: 29 },
        spawnBack: { tx: 25, ty: 9 },
      },
      {
        tx: 32,
        ty: 7,
        to: "gatos",
        label: "Ciudad de Gatos",
        spawnThere: { tx: 8, ty: 9 },
        spawnBack: { tx: 33, ty: 9 },
      },
      {
        tx: 33,
        ty: 7,
        to: "gatos",
        label: "",
        spawnThere: { tx: 8, ty: 9 },
        spawnBack: { tx: 33, ty: 9 },
      },
      {
        tx: 34,
        ty: 7,
        to: "gatos",
        label: "",
        spawnThere: { tx: 8, ty: 9 },
        spawnBack: { tx: 33, ty: 9 },
      },
    ],
    counter: true,
  },
  frawens: {
    id: "frawens",
    name: "Casa Frawens",
    rows: rowsOf([
      "####################",
      "####################",
      "####################",
      "####################",
      "####################",
      "####################",
      "####################",
      "####################",
      "#####...........####",
      "#####...........####",
      "#####...........####",
      "#####...........####",
      "#####...........####",
      "#####...........####",
      "#####...........####",
      "#####...........####",
      "#####.###..###..####",
      "#####.###..###..####",
      "#####...........####",
      "#####.###..###..####",
      "#####.###..###..####",
      "#####...........####",
      "#####...........####",
      "########....########",
      "########....########",
      "########.....#######",
      "########...#########",
      "####################",
    ]),
    floor: ["#2a2438", "#241e32"],
    wall: "#16141c",
    spawn: { tx: 10, ty: 25 },
    exits: [
      { tx: 8, ty: 26 },
      { tx: 9, ty: 26 },
      { tx: 10, ty: 26 },
    ],
    coin: { id: "frawens", tx: 10, ty: 8 },
    npcs: [
      {
        id: "jose",
        tx: 12,
        ty: 25,
        ox: 8,
        name: "José",
        dir: "down",
        visible: true,
        portrait: "assets/jose-walk.png?v=1",
        sheet: {
          cellW: 104,
          cellH: 214,
          idle: 0,
          walk: [0],
          foot: 4,
          scale: 36 / 214,
          dirs: { down: 0, right: 0, up: 0, left: 0 },
        },
        lines: [
          "José",
          "Pará. Al salón no se entra así nomás.",
          "Respondé bien y te dejo pasar.",
          "Por vos:",
        ],
        quiz: {
          options: [
            "Estoy viviendo arrepentido",
            "Mi pasado fue divino",
            "Vivi los mas lindos momentos",
            "Todas las anteriores",
          ],
          correct: 3,
          gate: "frawens",
          win: ["Bien. Pasá."],
          lose: ["No. Así no entrás.", "Pensala de nuevo."],
          done: ["Ya te dije que pases.", "Entrá."],
        },
      },
    ],
    doors: [],
    counter: false,
    signs: [],
  },
  tilos: {
    id: "tilos",
    name: "Los Tilos",
    rows: rowsOf([
      "########################################",
      "#CCCgCCCgggggggggggggggggggggggCCCgCCCg#",
      "#CCCgCCCgggggggggggggggggggggggCCCgCCCg#",
      "#gggggggggggggggggggggggggggggggggggggg#",
      "#gg=L==============================L=gg#",
      "#gg=ggggggggggggggg=gggggggggggggggg=gg#",
      "#gg=ggggggggggggggg=gggggggggggggggg=gg#",
      "#gg=ggggggggggggggg=gggggggggggggggg=gg#",
      "#gg=ggggWWWWWWWWWWWWWWWWWWWWWWWWgggg=gg#",
      "#gg=ggggW,BBBBBBB,,............Wgggg=gg#",
      "#gg=ggggW,BBBBBBB,,............Wgggg=gg#",
      "#gg=LgggW,,,,,,,,,,.......SSSSKWgggL=gg#",
      "#gg=====WP,,,,,,,,P.......SSSSKW=====gg#",
      "#gg=ggggW,,TT,,TT,,.......SSSSSWgggg=gg#",
      "#gg=ggggW,,TT,,TT,,.......SSSSSWgggg=gg#",
      "#gg=GgGgW,,,,,,,,,,.......SSSSSWgGgG=gg#",
      "#gg=GGGgWP,,,,,,,,P.......SSSSSWgGGG=gg#",
      "#gg=GgGgW,,TT,,TT,,.......SSSSSWgGgG=gg#",
      "#gg=ggggW,,TT,,TT,,.......SSSSSWgggg=gg#",
      "#gg=ggggWP,,,,,,,,,.......SSSSKWgggg=gg#",
      "#gg=ggggW,,,TT,,,,P.......SSSSKWgggg=gg#",
      "#gg=ggggW,,,TT,,,,,............Wgggg=gg#",
      "#gg=====W,,,,,,,,,,............W=====gg#",
      "#gg=ggggWWWWWWWWWWppppWWWWWWWWWWgggg=gg#",
      "#gg=ggggggggggggggppppgggggggggggggg=gg#",
      "#gg=ggggggggggggggppppgggggggggggggg=gg#",
      "#gg=ggggggggggggggppppgggggggggggggg=gg#",
      "#gg=LgggggggggggggppppgggggggggggggL=gg#",
      "#gg=ggggggggggggggppppgggggggggggggg=gg#",
      "#gg=L=============pppp=============L=gg#",
      "#gggggggggggggggggddddggggggggggggggggg#",
      "#CCCgCCCgggggggggggggggggggggggCCCgCCCg#",
      "#CCCgCCCgggggggggggggggggggggggCCCgCCCg#",
      "########################################",
    ]),
    floor: ["#1a4630", "#16402c"],
    wall: "#0c2016",
    spawn: { tx: 20, ty: 15 },
    exits: [
      { tx: 18, ty: 28 },
      { tx: 19, ty: 28 },
      { tx: 20, ty: 28 },
      { tx: 21, ty: 28 },
    ],
    coin: null,
    npcs: [
      {
        id: "nachito",
        tx: 18,
        ty: 13,
        name: "Nachito Saralegui",
        dir: "down",
        visible: true,
        portrait: "assets/nachito-walk.png?v=59",
        sheet: {
          cellW: 140,
          cellH: 205,
          idle: 0,
          walk: [0, 0, 0, 0],
          foot: 2,
          scale: WORLD_PX / 165,
          dirs: { down: 0, right: 1, up: 2, left: 3 },
        },
        lines: [
          "Nachito Saralegui",
          "Che, ¿cómo va? Soy Nachito Saralegui.",
          "Si querés una moneda, tenés que responder bien una pregunta de la banda.",
          "¿Cómo se llama el disco de La Trifulca?",
        ],
        quiz: {
          options: [
            "Mira en vos",
            "Gira en vos",
            "Lastima a Nadie maestro",
            "Atiendo boludos",
          ],
          correct: 1,
          coinId: "tilos",
          land: { tx: 19, ty: 14 },
          win: ["¡Bien ahí!", "Gira en vos. Ahí te revoleo la moneda."],
          lose: ["Nop, esa no es.", "Pensala de nuevo y volvé a hablarme."],
          done: ["Ya te tiré la moneda.", "Andá a buscarla al piso."],
        },
      },
    ],
    doors: [],
    counter: false,
    signs: [],
  },
  universal: {
    id: "universal",
    name: "Universal",
    rows: rowsOf([
      "########################",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "########################",
      "########################",
      ".......##########.......",
      ".......##########.......",
      ".......##########.......",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########.dd...#########",
      "########################",
    ]),
    floor: ["#2a2e34", "#242830"],
    wall: "#141820",
    spawn: { tx: 11, ty: 26 },
    exits: [
      { tx: 10, ty: 28 },
      { tx: 11, ty: 28 },
      { tx: 12, ty: 28 },
      { tx: 13, ty: 28 },
    ],
    coin: null,
    npcs: [
      {
        id: "nahuel",
        tx: 21,
        ty: 12,
        name: "Nahuel Piscitelli",
        dir: "down",
        visible: true,
        portrait: "assets/nahuel-walk.png?v=1",
        sheet: {
          cellW: 141,
          cellH: 155,
          idle: 0,
          walk: [0, 0, 0, 0],
          foot: 2,
          scale: WORLD_PX / 124,
          dirs: { down: 0, right: 0, up: 0, left: 0 },
        },
        lines: [
          "Che, ¿cómo va? Soy Nahuel Piscitelli.",
          "Si querés una moneda, tenés que responder bien una pregunta de la banda.",
          "¿En qué año salió el primer disco de la banda?",
        ],
        quiz: {
          options: ["2014", "2015", "2016", "2017"],
          correct: 1,
          coinId: "universal",
          land: { tx: 20, ty: 12 },
          win: ["¡Bien ahí!", "2015. Ahí te revoleo la moneda."],
          lose: ["Nop, esa no es.", "Pensala de nuevo y volvé a hablarme."],
          done: ["Ya te tiré la moneda.", "Andá a buscarla al piso."],
        },
      },
      {
        id: "picachu",
        tx: 9,
        ty: 6,
        ox: 8,
        oy: -8,
        name: "Picachu",
        dir: "down",
        visible: true,
        silent: true,
        portrait: "assets/picachu-walk.png?v=1",
        sheet: {
          cellW: 45,
          cellH: 47,
          idle: 0,
          walk: [0, 0, 0, 0],
          foot: 1,
          scale: WORLD_PX / 22,
          dirs: { down: 0, right: 0, up: 0, left: 0 },
        },
        lines: [],
      },
      { tx: 8, ty: 17, name: "En la esquina", lines: ["Universal. La esquina no daba más.", "La moneda la tiene Nahuel, en la senda de arriba."] },
      { tx: 14, ty: 17, name: "En el público", lines: ["El escenario quedó vacío.", "Se venía La Trifulca."] },
    ],
    doors: [],
    counter: false,
    signs: [],
  },
  moreno: {
    id: "moreno",
    name: "Plaza Moreno",
    rows: rowsOf([
      "##############################################################################################################",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "#............................................................................................................#",
      "##############################################################################################################",
    ]),
    floor: ["#c4b49a", "#b8a88e"],
    wall: "#3a342c",
    spawn: { tx: 54, ty: 29 },
    exits: [
      { tx: 54, ty: 26 },
      { tx: 55, ty: 26 },
      { tx: 54, ty: 27 },
      { tx: 55, ty: 27 },
    ],
    coin: null,
    npcs: [],
    doors: [],
    counter: false,
    signs: [],
  },
  gatos: {
    id: "gatos",
    name: "Ciudad de Gatos",
    rows: blankRows(18, 12),
    floor: ["#6a5344", "#5c483c"],
    wall: "#1a120e",
    spawn: { tx: 8, ty: 9 },
    exits: [],
    coin: null,
    npcs: [],
    doors: [],
    counter: false,
    signs: [],
  },
};

window.GAME_DATA = {
  TILE,
  CHARACTERS,
  MAPS,
};
for (let tx = 5; tx <= 9; tx += 1) {
  MAPS.gatos.exits.push({ tx, ty: 11 });
}
})();
