/** @typedef {{ tx: number, ty: number }} Tile */

(() => {
const TILE = 16;
const WORLD_PX = 24;

/** @type {readonly { id: string, name: string, role: string, portrait: string, sheet?: { cellW: number, cellH: number, idle: number, walk: readonly number[], foot: number, scale: number, dirs: Record<string, number> } }[]} */
const CHARACTERS = [
  {
    id: "ima",
    name: "Ima",
    role: "Cantante",
    portrait: "assets/ima-walk.png?v=18",
    sheet: {
      cellW: 65,
      cellH: 94,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 94,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "tobi",
    name: "Tobi",
    role: "Guitarra",
    portrait: "assets/tobi-walk.png?v=18",
    sheet: {
      cellW: 52,
      cellH: 80,
      idle: 0,
      walk: [0, 1, 2, 3],
      foot: 2,
      scale: WORLD_PX / 80,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "negro",
    name: "El Negro",
    role: "Teclado",
    portrait: "assets/negro-walk.png?v=20",
    sheet: {
      cellW: 117,
      cellH: 159,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 159,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "alvin",
    name: "Alvin",
    role: "Saxo",
    portrait: "assets/alvin-walk.png?v=21",
    sheet: {
      cellW: 110,
      cellH: 146,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 146,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "ger",
    name: "Ger",
    role: "Batería",
    portrait: "assets/ger-walk.png?v=24",
    sheet: {
      cellW: 124,
      cellH: 150,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 150,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "colito",
    name: "Colito",
    role: "Bajo",
    portrait: "assets/colito-walk.png?v=23",
    sheet: {
      cellW: 123,
      cellH: 154,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 154,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "nacho",
    name: "Nacho",
    role: "Timbales",
    portrait: "assets/nacho-walk.png?v=27",
    sheet: {
      cellW: 104,
      cellH: 134,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 134,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
  {
    id: "jerry",
    name: "Jerry",
    role: "Güiro",
    portrait: "assets/jerry-walk.png?v=27",
    sheet: {
      cellW: 104,
      cellH: 136,
      idle: 0,
      walk: [1, 2, 3, 4],
      foot: 2,
      scale: WORLD_PX / 136,
      dirs: { down: 0, right: 1, up: 2, left: 3 },
    },
  },
];

/**
 * @param {readonly string[]} rows
 * @returns {readonly string[]}
 */
function rowsOf(rows) {
  const width = rows[0].length;
  for (const row of rows) {
    if (row.length !== width) {
      throw new Error("Mapa con filas de distinto ancho");
    }
  }
  return rows;
}

const PASILLO_ROWS = rowsOf([
  "#########################",
  "#########################",
  "#########################",
  "#########################",
  "#########################",
  "#########################",
  "####..###..###..###.bbb##",
  "##.................bbb###",
  "##.................bbb###",
  "##.....................##",
  "#########################",
  "#########################",
  "#########################",
  "#########################",
]);

const ROOM_ROWS = rowsOf([
  "################",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#..............#",
  "#......dd......#",
  "################",
]);

/**
 * @param {string} id
 * @param {string} name
 * @param {readonly [string, string]} floor
 * @param {string} line
 */
function room(id, name, floor, line) {
  return {
    id,
    name,
    rows: ROOM_ROWS,
    floor,
    wall: "#1a120e",
    spawn: { tx: 7, ty: 10 },
    exits: [
      { tx: 6, ty: 12 },
      { tx: 7, ty: 12 },
      { tx: 8, ty: 12 },
      { tx: 9, ty: 12 },
    ],
    coin: { id, tx: 8, ty: 3 },
    npcs: [{ tx: 4, ty: 8, name: "Alguien del lugar", lines: [line, "Hay una moneda en el piso."] }],
    doors: [],
    counter: false,
  };
}

const MAPS = {
  pasillo: {
    id: "pasillo",
    name: "Pasillo",
    rows: PASILLO_ROWS,
    floor: ["#3a3128", "#332b23"],
    wall: "#1a120e",
    spawn: { tx: 12, ty: 8 },
    exits: [],
    coin: null,
    npcs: [],
    doors: [
      {
        tx: 4,
        ty: 6,
        to: "frawens",
        label: "Casa Frawens",
        spawnThere: { tx: 11, ty: 23 },
        spawnBack: { tx: 4, ty: 8 },
      },
      {
        tx: 5,
        ty: 6,
        to: "frawens",
        label: "",
        spawnThere: { tx: 11, ty: 23 },
        spawnBack: { tx: 5, ty: 8 },
      },
      {
        tx: 4,
        ty: 7,
        to: "frawens",
        label: "",
        spawnThere: { tx: 11, ty: 23 },
        spawnBack: { tx: 4, ty: 8 },
      },
      {
        tx: 5,
        ty: 7,
        to: "frawens",
        label: "",
        spawnThere: { tx: 11, ty: 23 },
        spawnBack: { tx: 5, ty: 8 },
      },
      {
        tx: 9,
        ty: 6,
        to: "tilos",
        label: "Los Tilos",
        spawnThere: { tx: 20, ty: 15 },
        spawnBack: { tx: 9, ty: 8 },
      },
      {
        tx: 10,
        ty: 6,
        to: "tilos",
        label: "",
        spawnThere: { tx: 20, ty: 15 },
        spawnBack: { tx: 10, ty: 8 },
      },
      {
        tx: 9,
        ty: 7,
        to: "tilos",
        label: "",
        spawnThere: { tx: 20, ty: 15 },
        spawnBack: { tx: 9, ty: 8 },
      },
      {
        tx: 10,
        ty: 7,
        to: "tilos",
        label: "",
        spawnThere: { tx: 20, ty: 15 },
        spawnBack: { tx: 10, ty: 8 },
      },
      {
        tx: 14,
        ty: 6,
        to: "universal",
        label: "Universal",
        spawnThere: { tx: 11, ty: 18 },
        spawnBack: { tx: 14, ty: 8 },
      },
      {
        tx: 15,
        ty: 6,
        to: "universal",
        label: "",
        spawnThere: { tx: 11, ty: 18 },
        spawnBack: { tx: 15, ty: 8 },
      },
      {
        tx: 14,
        ty: 7,
        to: "universal",
        label: "",
        spawnThere: { tx: 11, ty: 18 },
        spawnBack: { tx: 14, ty: 8 },
      },
      {
        tx: 15,
        ty: 7,
        to: "universal",
        label: "",
        spawnThere: { tx: 11, ty: 18 },
        spawnBack: { tx: 15, ty: 8 },
      },
    ],
    counter: true,
  },
  frawens: {
    id: "frawens",
    name: "Casa Frawens",
    rows: rowsOf([
      "########################",
      "########################",
      "########################",
      "#SSSSSSSSSSSSSSSSSSSSSS#",
      "#BB...................P#",
      "#BB..TT......TT.......P#",
      "#BB..TT......TT.......P#",
      "#BB...................P#",
      "#BB..TT......TT.......P#",
      "#BB..TT......TT.......P#",
      "#BB...................P#",
      "#BB..TT......TT.......P#",
      "#BB..TT......TT.......P#",
      "#BB...................P#",
      "#BB..TT......TT.......P#",
      "#BB..TT......TT.......P#",
      "#BB...................P#",
      "#......................#",
      "#......................#",
      "#......................#",
      "#......................#",
      "####................####",
      "#oo..................oo#",
      "#oo......dd..........oo#",
      "#oo......dd..........oo#",
      "#oo......dd..........oo#",
      "########################",
      "########################",
    ]),
    floor: ["#2a2438", "#241e32"],
    wall: "#16141c",
    spawn: { tx: 11, ty: 23 },
    exits: [
      { tx: 10, ty: 23 },
      { tx: 11, ty: 23 },
      { tx: 12, ty: 23 },
      { tx: 10, ty: 24 },
      { tx: 11, ty: 24 },
      { tx: 12, ty: 24 },
      { tx: 10, ty: 25 },
      { tx: 11, ty: 25 },
      { tx: 12, ty: 25 },
    ],
    coin: { id: "frawens", tx: 11, ty: 14 },
    npcs: [
      { tx: 4, ty: 7, name: "En la barra", lines: ["No daban abasto.", "La moneda está en la pista."] },
      { tx: 11, ty: 10, name: "En la pista", lines: ["Los espejos tiraban para todos lados."] },
      { tx: 16, ty: 12, name: "En las mesas", lines: ["No quedaba una libre."] },
    ],
    doors: [],
    counter: false,
    signs: [],
  },
  tilos: {
    id: "tilos",
    name: "Los Tilos",
    rows: rowsOf([
      "########################################",
      "#CCCgCCCgggggggggggggggggggggggCCCgCCCg#",
      "#CCCgCCCgggggggggggggggggggggggCCCgCCCg#",
      "#gggggggggggggggggggggggggggggggggggggg#",
      "#gg=L==============================L=gg#",
      "#gg=ggggggggggggggg=gggggggggggggggg=gg#",
      "#gg=ggggggggggggggg=gggggggggggggggg=gg#",
      "#gg=ggggggggggggggg=gggggggggggggggg=gg#",
      "#gg=ggggWWWWWWWWWWWWWWWWWWWWWWWWgggg=gg#",
      "#gg=ggggW,BBBBBBB,,............Wgggg=gg#",
      "#gg=ggggW,BBBBBBB,,............Wgggg=gg#",
      "#gg=LgggW,,,,,,,,,,.......SSSSKWgggL=gg#",
      "#gg=====WP,,,,,,,,P.......SSSSKW=====gg#",
      "#gg=ggggW,,TT,,TT,,.......SSSSSWgggg=gg#",
      "#gg=ggggW,,TT,,TT,,.......SSSSSWgggg=gg#",
      "#gg=GgGgW,,,,,,,,,,.......SSSSSWgGgG=gg#",
      "#gg=GGGgWP,,,,,,,,P.......SSSSSWgGGG=gg#",
      "#gg=GgGgW,,TT,,TT,,.......SSSSSWgGgG=gg#",
      "#gg=ggggW,,TT,,TT,,.......SSSSSWgggg=gg#",
      "#gg=ggggWP,,,,,,,,,.......SSSSKWgggg=gg#",
      "#gg=ggggW,,,TT,,,,P.......SSSSKWgggg=gg#",
      "#gg=ggggW,,,TT,,,,,............Wgggg=gg#",
      "#gg=====W,,,,,,,,,,............W=====gg#",
      "#gg=ggggWWWWWWWWWWppppWWWWWWWWWWgggg=gg#",
      "#gg=ggggggggggggggppppgggggggggggggg=gg#",
      "#gg=ggggggggggggggppppgggggggggggggg=gg#",
      "#gg=ggggggggggggggppppgggggggggggggg=gg#",
      "#gg=LgggggggggggggppppgggggggggggggL=gg#",
      "#gg=ggggggggggggggppppgggggggggggggg=gg#",
      "#gg=L=============pppp=============L=gg#",
      "#gggggggggggggggggddddggggggggggggggggg#",
      "#CCCgCCCgggggggggggggggggggggggCCCgCCCg#",
      "#CCCgCCCgggggggggggggggggggggggCCCgCCCg#",
      "########################################",
    ]),
    floor: ["#1a4630", "#16402c"],
    wall: "#0c2016",
    spawn: { tx: 20, ty: 15 },
    exits: [
      { tx: 18, ty: 28 },
      { tx: 19, ty: 28 },
      { tx: 20, ty: 28 },
      { tx: 21, ty: 28 },
    ],
    coin: { id: "tilos", tx: 26, ty: 12 },
    npcs: [
      {
        id: "nachito",
        tx: 11,
        ty: 15,
        name: "Nachito Saralegui",
        dir: "down",
        visible: true,
        portrait: "assets/nachito-walk.png?v=55",
        sheet: {
          cellW: 82,
          cellH: 188,
          idle: 0,
          walk: [0, 0, 0, 0],
          foot: 2,
          scale: WORLD_PX / 188,
          dirs: { down: 0, right: 1, up: 2, left: 3 },
        },
        lines: [
          "Nachito Saralegui",
          "Che, ¿cómo va? Soy Nachito Saralegui.",
          "Si querés una moneda, tenés que responder bien una pregunta de la banda.",
          "¿Cómo se llama el disco de La Trifulca?",
        ],
        quiz: {
          options: [
            "Mira en vos",
            "Gira en vos",
            "Lastima a Nadie maestro",
            "Atiendo boludos",
          ],
          correct: 1,
          coinId: "tilos",
          win: ["¡Bien ahí!", "Gira en vos. Tomá la moneda."],
          lose: ["Nop, esa no es.", "Pensala de nuevo y volvé a hablarme."],
        },
      },
    ],
    doors: [],
    counter: false,
    signs: [],
  },
  universal: {
    id: "universal",
    name: "Universal",
    rows: rowsOf([
      "########################",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "########################",
      "########################",
      ".......##########.......",
      ".......##########.......",
      ".......##########.......",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########......#########",
      "#########.dd...#########",
      "########################",
    ]),
    floor: ["#2a2e34", "#242830"],
    wall: "#141820",
    spawn: { tx: 11, ty: 18 },
    exits: [
      { tx: 10, ty: 28 },
      { tx: 11, ty: 28 },
      { tx: 12, ty: 28 },
      { tx: 13, ty: 28 },
    ],
    coin: { id: "universal", tx: 11, ty: 16 },
    npcs: [
      { tx: 8, ty: 17, name: "En la esquina", lines: ["Universal. La esquina no daba más.", "La moneda está frente al escenario."] },
      { tx: 14, ty: 17, name: "En el público", lines: ["El escenario quedó vacío.", "Se venía La Trifulca."] },
    ],
    doors: [],
    counter: false,
    signs: [],
  },
};

window.GAME_DATA = {
  TILE,
  CHARACTERS,
  MAPS,
};
})();
